# Set the listening address and port
listen_addresses: '0.0.0.0:3010'

# Set the base path for TileJSON URLs
base_path: /tiles

# Increase the number of worker processes for better performance
worker_processes: 4

# Increase cache size for better performance
cache_size_mb: 1024

# Enable gzip compression for faster transfer
preferred_encoding: gzip

# Disable web UI for production use
web_ui: enable

# PostgreSQL configuration
postgres:
  connection_string: ${DATABASE_URL:-postgresql://postgres:p4ik5IdbSwQBMaUNBUgashGjZUxBhkN9Autx9R9Yj9VeXNgOIMYzhIuapPKn8ti1@135.181.108.171:5432/postgres}
  default_srid: 4326
  pool_size: 20
  max_feature_count: 10000
  auto_bounds: quick
  auto_publish:
    tables:
      source_id_format: '{table}'
      clip_geom: true
      buffer: 64
      extent: 4096


# MBTiles configuration
mbtiles:
  paths:
    - /tiles
  sources:
    sweden:
      path: /tiles/sweden.mbtiles
      minzoom: 0
      maxzoom: 14

# Sprite configuration (if you have any sprite images)
sprites:
  paths:
    - /sprites
# Font configuration (if you have any custom fonts)
fonts:
   - /fonts