services:
  osm2pgsql:
    image: iboates/osm2pgsql:latest
    container_name: osm2pgsql
    volumes:
      - ./data:/data
      - ./points.lua:/points.lua
    env_file:
      - .env
    entrypoint:
      - /bin/sh
      - -c
      - |
        wget -O /data/sweden-latest.osm.pbf $$OSM_PBF_SWEDEN_URL &&
        osm2pgsql \
          --create \
          --slim \
          --database $$PGDATABASE \
          -U $$PGUSER \
          -H $$PGHOST \
          -P $$PGPORT \
          -C $${CACHE_SIZE:-1500} \
          --number-processes $${NUM_PROCESSES:-8} \
          --extra-attributes \
          --output=flex \
          --style /points.lua \
          --verbose \
          /data/sweden-latest.osm.pbf

    restart: no
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 6G