services:

  osm2pgsql:
    image: iboates/osm2pgsql:latest
    container_name: osm2pgsql
    volumes:
      - ./data:/osm-data
      - ./points.lua:/points.lua
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      wget -O /osm-data/data.pbf $$OSM_PBF_SWEDEN_URL &&
      osm2pgsql \
      --create \
      --slim \
      --database $$PGDATABASE -U $$PGUSER -H $$PGHOST -P $$PGPORT -C 4000 \
      --number-processes 1 \
      --extra-attributes \
      --output=flex \
      --style=/points.lua \
      --verbose \
      /osm-data/data.pbf
      "
    restart: no